spring.application.name: test.yaml

default-value-ref: app-test

# 设置 runner 收集顺序
command-line-runner:
  collection: "*,github.com/go-spring/examples/spring-boot-demo/app/app.MyRunner:MyRunner"

# 设置 starter 收集顺序
application-event:
  collection: "*,github.com/go-spring/starter-web/StarterWeb.Starter:Starter"